name: build container
run-name: building container
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - base
        run: |
          podman build -t ghcr.io/gbraad-apps/code:latest \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/rdesktop" \
            --build-arg=BASE_VERSION=41 \
            -f ./containers/Containerfile-base .
      - name: Push image to ghcr.io - base
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-apps/code:latest
      - name: Run podman build - serve-web
        run: |
          podman build -t ghcr.io/gbraad-apps/code-serveweb:latest \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-apps/code" \
            --build-arg=BASE_VERSION=latest \
            --build-arg=USER="gbraad" \
            -f ./containers/Containerfile .
      - name: Push image to ghcr.io - serve-web
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-apps/code-serveweb:latest
