name: tailscale-serveweb
on:
  workflow_dispatch:

jobs:
  serveweb-test:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Run system container with `podman`
        run: |
          podman run -d --name rdesktop \
            --cap-add=NET_ADMIN --cap-add=NET_RAW --device=/dev/net/tun --device=/dev/fuse \
            ghcr.io/gbraad-apps/code-serveweb:latest
      - name: Tailscale setup (root)
        run: |
          until podman exec rdesktop tailscale up --auth-key ${TAILSCALE_AUTHKEY} --hostname github-${HOSTNAME}
          do
              sleep 0.1
          done
          podman exec rdesktop tailscale set --ssh
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY}}
      - name: Hang around
        run: |
          until podman exec rdesktop systemctl is-active --quiet kasmvncserver
          do
               sleep 1
          done
          #until podman exec rdesktop systemctl is-active --quiet code-serveweb@gbraad
          #do
          #     sleep 1
          #done
          IP=`podman exec rdesktop tailscale ip -4`
          echo "Open in your web browser: https://${IP}:8444"
          sleep infinity
